[project]
name = "java-copier-template"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "copier>=9.6.0",
    "copier-templates-extensions>=0.3.1",
    "mypy>=1.15.0",
]
